POST http://localhost:3000/acadia_finder_db/sales
Content-Type: application/json

{
  "salesId": "011jlksjdf",
  "sellerId": "03khfjksdf",
  "purchaserId": "isjdflkjs",
  "bookId": "jklsjdf",
  "dateSold": "08/08/08",
  "listedPrice": 9000
}
###
POST http://localhost:3000/books
Content-Type: application/json

{
  "name": "011jlksjdfre",
  "courseId": "03khfjksdffds",
  "edition": "isjdflkjsfs",
  "author": "jklsjdffds",
  "bookImage": "fsdfadsfas",
  "userId": "fsdfsd4",
  "buyPrice": 9000,
  "rentPrice": 9000,
  "forRent": true,
  "forSale": false
}

###

GET http://localhost:3000/books

###
DELETE http://localhost:3000/books/616789aeaf29979a70e4a501

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "userName": "Muhammad",
  "password": "112233",
  "firstName": "Muhammad",
  "lastName": "Akbar",
  "phoneNumber": "902-648-3002",
  "email": "makbar@gmail.com",
  "major": "Computer Science"
}

###

GET http://localhost:3000/users

###
DELETE http://localhost:3000/users/616789aeaf29979a70e4a501
