POST http://localhost:3000/acadia_finder_db/sales
Content-Type: application/json

{
  "salesId": "011jlksjdf",
  "sellerId": "03khfjksdf",
  "purchaserId": "isjdflkjs",
  "bookId": "jklsjdf",
  "dateSold": "08/08/08",
  "listedPrice": 9000
}
###
POST http://localhost:3000/books
Content-Type: application/json

{
  "name": "011jlksjdfre",
  "courseId": "03khfjksdffds",
  "edition": "isjdflkjsfs",
  "author": "jklsjdffds",
  "bookImage": "fsdfadsfas",
  "userId": "fsdfsd4",
  "buyPrice": 9000,
  "rentPrice": 9000,
  "forRent": true,
  "forSale": true
}

###

GET http://localhost:3000/books

###

DELETE http://localhost:3000/books

###

GET http://localhost:3000/comments

###

DELETE http://localhost:3000/comments

###

GET http://localhost:3000/books/617c00fd88c7d3944755055d

###
DELETE http://localhost:3000/books/617c00fd88c7d3944755055d

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "userName": "Muhammad",
  "password": "112233",
  "firstName": "Muhammad",
  "lastName": "Akbar",
  "phoneNumber": "902-648-3002",
  "email": "makbar@gmail.com",
  "major": "Computer Science"
}

###

GET http://localhost:3000/users

###

GET http://localhost:3000/users/617da58dab4ecd46974ea7351/friendship

###
DELETE http://localhost:3000/users/617c0d603b67bc21014c08d0

###
POST http://localhost:3000/notes
Content-Type: application/json

{
  "courseId": "courseid1",
  "providerId": "pid1",
  "noteFile": "This will be the file",
  "datePosted": "08/08/00",
  "description": "This is the note for the class yeee",
  "semester": "FA22"
}

###

GET http://localhost:3000/notes

###
DELETE http://localhost:3000/notes/616789aeaf29979a70e4a501

###
POST http://localhost:3000/friendship
Content-Type: application/json

{
  "requester": "courseid1",
  "recipient": "pid1",
  "status": "This will be the file",
}

###

GET http://localhost:3000/friendship

###
DELETE http://localhost:3000/friendship/616789aeaf29979a70e4a501

###

GET http://localhost:3000/friendship